services:
  - type: web
    name: fastapi-capcheck
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app/listen.py
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: supabase-db
          property: connectionString
