services:
  - type: web
    name: fastapi-capcheck
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python3 listen.py
    envVars:
      - key: ENV
        value: production
        sync: false